### ISSUE TITLE
Allow for `indent` as a `json.dumps` parameter

### ISSUE THREAD

**Issue by twolfson** [uber/cassette#38]
Upon reviewing the documentation, I discovered JSON encode and directory storage which is awesome for cleaning up out of date fixtures. Also, I saw reporting of unused fixtures which is really cool and I want to consider bringing over to `nine-track` =3

Anyway, I was wondering if we would be open to either setting an `indent` on `json.dumps` as a default or allowing it to be set as a configuration option. When scrolling through POST requests, it is hard to see the POST body without beautifying every file I open.

**Comment by charlax** [comment]
Sure! That sounds a great idea!

**Comment by twolfson** [comment]
I think I might have been ambiguous on the proposed change. Which behavior would we prefer:

- Move `json.dumps` to always use `indent` and don't support an `indent` flag in its config
- Move `json.dumps` to always use `indent` and support an `indent` flag in its config
- Keep `json.dumps` without an `indent` and support an `indent` flag in its config

**Comment by charlax** [comment]
I'd say the first :) Probably the simplest, most people will want this, and the cost is minimum.
